# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170505_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name for this item', max_length=100)),
                ('name_en', models.CharField(help_text='The name for this item', max_length=100, null=True)),
                ('long_description', models.TextField(blank=True, help_text='Description text used when this item is displayed on a full page', null=True)),
                ('long_description_en', models.TextField(blank=True, help_text='Description text used when this item is displayed on a full page', null=True)),
                ('short_description', models.TextField(blank=True, help_text='Description text used when this item is shown in a list. It will also be shown in bold format in front of the long description on full page displays', null=True)),
                ('short_description_en', models.TextField(blank=True, help_text='Description text used when this item is shown in a list. It will also be shown in bold format in front of the long description on full page displays', null=True)),
                ('slug', models.CharField(blank=True, help_text='This field is used for links, it should usually be the name with spaces replaced by an underscore', max_length=100, null=True)),
                ('slug_en', models.CharField(blank=True, help_text='This field is used for links, it should usually be the name with spaces replaced by an underscore', max_length=100, null=True)),
                ('sort_order', models.IntegerField(default=500, help_text='The order in which this item will show on list pages')),
                ('max_milage', models.DecimalField(decimal_places=2, help_text='The maximum miles allowed for this rate', max_digits=15)),
                ('dump_rate', models.DecimalField(blank=True, decimal_places=2, help_text='The price for dump truck delivery', max_digits=15, null=True)),
                ('flatbed_rate', models.DecimalField(blank=True, decimal_places=2, help_text='The price for flatbed delivery', max_digits=15, null=True)),
                ('lookup_id', models.CharField(default=None, help_text='Quickbooks Lookup', max_length=15)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
