# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_deliverycharge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverycharge',
            options={'ordering': ['lookup_id']},
        ),
        migrations.AddField(
            model_name='product',
            name='sold_out',
            field=models.NullBooleanField(default=False, help_text='Display a Sold Out Image over the product image'),
        ),
    ]
