# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-29 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='header_color',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
