# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20160331_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttype',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='description_es',
        ),
        migrations.AddField(
            model_name='contentpage',
            name='long_description_en',
            field=models.TextField(help_text=b'Description text used when this item is displayed on a full page', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='contentpage',
            name='long_description_es',
            field=models.TextField(help_text=b'Description text used when this item is displayed on a full page', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='contentpage',
            name='name_en',
            field=models.CharField(help_text=b'The name for this item', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='contentpage',
            name='name_es',
            field=models.CharField(help_text=b'The name for this item', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='contentpage',
            name='short_description_en',
            field=models.TextField(help_text=b'Description text used when this item is shown in a list. It will also be shown in bold format in front of the long description on full page displays', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='contentpage',
            name='short_description_es',
            field=models.TextField(help_text=b'Description text used when this item is shown in a list. It will also be shown in bold format in front of the long description on full page displays', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='contentpage',
            name='slug_en',
            field=models.CharField(help_text=b'This field is used for links, it should usually be the name with spaces replaced by an underscore', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='contentpage',
            name='slug_es',
            field=models.CharField(help_text=b'This field is used for links, it should usually be the name with spaces replaced by an underscore', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='long_description_en',
            field=models.TextField(help_text=b'Description text used when this item is displayed on a full page', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='long_description_es',
            field=models.TextField(help_text=b'Description text used when this item is displayed on a full page', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='name_en',
            field=models.CharField(help_text=b'The name for this item', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='name_es',
            field=models.CharField(help_text=b'The name for this item', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='short_description_en',
            field=models.TextField(help_text=b'Description text used when this item is shown in a list. It will also be shown in bold format in front of the long description on full page displays', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='short_description_es',
            field=models.TextField(help_text=b'Description text used when this item is shown in a list. It will also be shown in bold format in front of the long description on full page displays', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='slug_en',
            field=models.CharField(help_text=b'This field is used for links, it should usually be the name with spaces replaced by an underscore', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='slug_es',
            field=models.CharField(help_text=b'This field is used for links, it should usually be the name with spaces replaced by an underscore', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='job',
            name='long_description_en',
            field=models.TextField(help_text=b'Description text used when this item is displayed on a full page', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='job',
            name='long_description_es',
            field=models.TextField(help_text=b'Description text used when this item is displayed on a full page', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='job',
            name='name_en',
            field=models.CharField(help_text=b'The name for this item', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='job',
            name='name_es',
            field=models.CharField(help_text=b'The name for this item', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='job',
            name='short_description_en',
            field=models.TextField(help_text=b'Description text used when this item is shown in a list. It will also be shown in bold format in front of the long description on full page displays', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='job',
            name='short_description_es',
            field=models.TextField(help_text=b'Description text used when this item is shown in a list. It will also be shown in bold format in front of the long description on full page displays', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='job',
            name='slug_en',
            field=models.CharField(help_text=b'This field is used for links, it should usually be the name with spaces replaced by an underscore', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='job',
            name='slug_es',
            field=models.CharField(help_text=b'This field is used for links, it should usually be the name with spaces replaced by an underscore', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='long_description_en',
            field=models.TextField(help_text=b'Description text used when this item is displayed on a full page', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='long_description_es',
            field=models.TextField(help_text=b'Description text used when this item is displayed on a full page', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_en',
            field=models.CharField(help_text=b'The name for this item', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_es',
            field=models.CharField(help_text=b'The name for this item', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='short_description_en',
            field=models.TextField(help_text=b'Description text used when this item is shown in a list. It will also be shown in bold format in front of the long description on full page displays', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='short_description_es',
            field=models.TextField(help_text=b'Description text used when this item is shown in a list. It will also be shown in bold format in front of the long description on full page displays', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='slug_en',
            field=models.CharField(help_text=b'This field is used for links, it should usually be the name with spaces replaced by an underscore', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='slug_es',
            field=models.CharField(help_text=b'This field is used for links, it should usually be the name with spaces replaced by an underscore', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='product',
            name='long_description_en',
            field=models.TextField(help_text=b'Description text used when this item is displayed on a full page', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='product',
            name='long_description_es',
            field=models.TextField(help_text=b'Description text used when this item is displayed on a full page', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(help_text=b'The name for this item', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='product',
            name='name_es',
            field=models.CharField(help_text=b'The name for this item', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.TextField(help_text=b'Description text used when this item is shown in a list. It will also be shown in bold format in front of the long description on full page displays', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_es',
            field=models.TextField(help_text=b'Description text used when this item is shown in a list. It will also be shown in bold format in front of the long description on full page displays', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='product',
            name='slug_en',
            field=models.CharField(help_text=b'This field is used for links, it should usually be the name with spaces replaced by an underscore', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='product',
            name='slug_es',
            field=models.CharField(help_text=b'This field is used for links, it should usually be the name with spaces replaced by an underscore', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='project',
            name='long_description_en',
            field=models.TextField(help_text=b'Description text used when this item is displayed on a full page', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='project',
            name='long_description_es',
            field=models.TextField(help_text=b'Description text used when this item is displayed on a full page', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.CharField(help_text=b'The name for this item', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='project',
            name='name_es',
            field=models.CharField(help_text=b'The name for this item', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_en',
            field=models.TextField(help_text=b'Description text used when this item is shown in a list. It will also be shown in bold format in front of the long description on full page displays', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_es',
            field=models.TextField(help_text=b'Description text used when this item is shown in a list. It will also be shown in bold format in front of the long description on full page displays', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='project',
            name='slug_en',
            field=models.CharField(help_text=b'This field is used for links, it should usually be the name with spaces replaced by an underscore', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='project',
            name='slug_es',
            field=models.CharField(help_text=b'This field is used for links, it should usually be the name with spaces replaced by an underscore', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projecttype',
            name='long_description_en',
            field=models.TextField(help_text=b'Description text used when this item is displayed on a full page', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projecttype',
            name='long_description_es',
            field=models.TextField(help_text=b'Description text used when this item is displayed on a full page', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projecttype',
            name='name_en',
            field=models.CharField(help_text=b'The name for this item', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projecttype',
            name='name_es',
            field=models.CharField(help_text=b'The name for this item', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projecttype',
            name='short_description_en',
            field=models.TextField(help_text=b'Description text used when this item is shown in a list. It will also be shown in bold format in front of the long description on full page displays', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projecttype',
            name='short_description_es',
            field=models.TextField(help_text=b'Description text used when this item is shown in a list. It will also be shown in bold format in front of the long description on full page displays', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projecttype',
            name='slug_en',
            field=models.CharField(help_text=b'This field is used for links, it should usually be the name with spaces replaced by an underscore', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projecttype',
            name='slug_es',
            field=models.CharField(help_text=b'This field is used for links, it should usually be the name with spaces replaced by an underscore', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='staffmember',
            name='long_description_en',
            field=models.TextField(help_text=b'Description text used when this item is displayed on a full page', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='staffmember',
            name='long_description_es',
            field=models.TextField(help_text=b'Description text used when this item is displayed on a full page', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='staffmember',
            name='name_en',
            field=models.CharField(help_text=b'The name for this item', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='staffmember',
            name='name_es',
            field=models.CharField(help_text=b'The name for this item', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='staffmember',
            name='short_description_en',
            field=models.TextField(help_text=b'Description text used when this item is shown in a list. It will also be shown in bold format in front of the long description on full page displays', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='staffmember',
            name='short_description_es',
            field=models.TextField(help_text=b'Description text used when this item is shown in a list. It will also be shown in bold format in front of the long description on full page displays', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='staffmember',
            name='slug_en',
            field=models.CharField(help_text=b'This field is used for links, it should usually be the name with spaces replaced by an underscore', max_length=100, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='staffmember',
            name='slug_es',
            field=models.CharField(help_text=b'This field is used for links, it should usually be the name with spaces replaced by an underscore', max_length=100, null=True),
            preserve_default=True,
        ),
    ]
