# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_auto_20160331_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='long_description_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='short_description_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_es',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='long_description_es',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='short_description_es',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='slug_es',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='long_description_es',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='short_description_es',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='slug_es',
        ),
        migrations.RemoveField(
            model_name='job',
            name='long_description_es',
        ),
        migrations.RemoveField(
            model_name='job',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='job',
            name='short_description_es',
        ),
        migrations.RemoveField(
            model_name='job',
            name='slug_es',
        ),
        migrations.RemoveField(
            model_name='location',
            name='long_description_es',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='location',
            name='short_description_es',
        ),
        migrations.RemoveField(
            model_name='location',
            name='slug_es',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='long_description_es',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='short_description_es',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='slug_es',
        ),
        migrations.RemoveField(
            model_name='product',
            name='long_description_es',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description_es',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_es',
        ),
        migrations.RemoveField(
            model_name='project',
            name='long_description_es',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_description_es',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug_es',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='long_description_es',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='short_description_es',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='slug_es',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='long_description_es',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='short_description_es',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='slug_es',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(to='web.Category', help_text=b'Parent category', null=True),
            preserve_default=True,
        ),
    ]
