# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-07 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_auto_20170225_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(help_text=b'Parent category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='web.Category'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
