# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-08 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_auto_20170308_2245'),
        ('web', '0028_auto_20170307_2007'),
    ]

    operations = [
    ]
