# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-23 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_merge'),
        ('web', '0030_auto_20170323_1410'),
    ]

    operations = [
    ]
