# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-03 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_auto_20170328_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='more_images_text',
            field=models.CharField(blank=True, default=b'More Images', help_text=b'Text to show above extra product images', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default=b'product/no_image.jpeg', help_text=b'The image to show for this item', null=True, upload_to=b'ProductImages/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
