# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-03 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_auto_20170403_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='name',
            field=models.CharField(blank=True, default=None, help_text=b'text to show above image', max_length=15, null=True),
        ),
    ]
